services:
  - type: web
    name: bimar-banda-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --preload --workers 1 --bind 0.0.0.0:10000"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PLACES_API_KEY
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH
        sync: false
      - key: TWILIO_PHONE
        sync: false